config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :events
  resources :attendances
  resources :charges
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  #after_create :new_participant

  belongs_to :guest, class_name: "User"
  belongs_to :event

  #def new_participant
    #AttendanceMailer.new_participant_email(self).deliver_now
  #end
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :administrator, class_name: "User"
  has_many :attendances
  has_many :guests, class_name: "User", through: :attendances

  validates :start_date,
  presence: true

  validates :duration,
  presence: true,
  numericality: { greater_than: 0 }

  validates :title,
  presence: true,
  length: { minimum: 5, maximum: 140 }

  validates :description,
  presence: true,
  length: { minimum: 10, maximum: 1000 }

  validates :price,
  presence: true,
  numericality: { greater_than: 1, less_than: 1000}

  validates :location,
  presence: true


  def is_event_passed?
    errors.add(:start_date, "L'évenement est déjà fini")
    if start_date < Time.now
    end
  end

  def correct_duration
    errors.add(:duration, "Durée incorrecte")
    unless duration % 5 == 0
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send
  
  has_many :events, foreign_key: 'administrator_id', class_name: "Event"
  has_many :attendances, foreign_key: 'guest_id', class_name: "Attendance"

  validates :email,
  presence: true,
  length: {minimum: 6 } 

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def new
    @attendance = Attendance.new
  end

  def create
    @attendance = Attendance.create(stripe_customer_id: params[:stripe_customer_id])
    @attendance.guest = current_user
    @attendance.event_id = params[:event_id]

    if @attendance.save
      redirect_to event_path(@attendance.event)
    else
      flash[:error] = "Ta participation n'a pas été prise en compte"
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @attendances = Attendance.all
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.create(title: params[:title], description: params[:description], start_date: params[:start_date], duration: params[:duration], price: params[:price], location: params[:location])
    @event.administrator = current_user

    if @event.save
      redirect_to @event
    else
      render 'new'
    end

    def subscription
    @event = Event.find(params[:id])
    @amount = @event.price * 100

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'eur'
    )

    redirect_to @event

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to @event
    end
  end

  def destroy
   @event = Event.find(params[:id])

   @event.destroy
   redirect_to events_path
 end

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to event_path
    else
    render :update
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :start_date, :duration, :price, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  
  def new
    @user = User.new
  end

  def create
    @user = User.create(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], password: params[:password], description: params[:description])

    if @user.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h1>Attendances#create</h1>
<p>Find me in app/views/attendances/create.html.erb</p>

app/views/attendances/destroy.html.erb
<h1>Attendances#destroy</h1>
<p>Find me in app/views/attendances/destroy.html.erb</p>

app/views/attendances/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Participer à l'évent</h5>
            <%= form_tag url_for(action: 'create'), method: "post", class: "form-signin" do %>

             <div class="form-label-group">
            	<%= text_field_tag 'title', @title, class: "form-control", id: "inputTitle", placeholder: "Titre", :required => true  %>
      		</div>

      		<div class="form-label-group">
                <%= text_field_tag 'description', @description, class: "form-control", id: "inputDescription", placeholder: "Description", :required => true  %>
              </div>

      		<div class="form-label-group">
            	<%= text_field_tag 'start_date', @start_date, class: "form-control", id: "inputStart_date", placeholder: "Date", :required => true %>
      		</div>

      		<div class="form-label-group">
            	<%= text_field_tag 'duration', @duration, class: "form-control", id: "inputDuration", placeholder: "Durée", :required => true  %>
      		</div>

      		<div class="form-label-group">
                <%= text_field_tag 'price', @price, class: "form-control", id: "inputPrice", placeholder: "Prix", :required => true  %>
              </div>

      		<div class="form-label-group">
            	<%= text_field_tag 'location', @location, class: "form-control", id: "inputLocation", placeholder: "Lieu", :required => true %>
      		</div>

      		<div class="form-group">
            	<%= submit_tag "Je participe", class: "btn btn-lg btn-primary btn-block text-uppercase" %>
      		</div>
          </div>
        </div>
      </div>
    </div>
    <% end %>	
</div>

app/views/attendances/show.html.erb
<% if @event.attendances.count == 0 %>
<h2 class="text-center my-5 mb-3">Il n'y a pas encore de participants à cet évenement</h2>

<% else %>

<h2 class="text-center mt-3 mb-3">Livre des Invités</h2>

<div class="container">
  <div class="card-deck mb-4 text-center">
    <% @event.attendances.each do |attendance| %>
    <div class="col-md-4">
      <div class="card border border-primary mt-3 shadow-sm" style="width: 18rem;">
        <div class="card-body">
          <h4 class="card-subtitle mb-5 text-muted"><%= attendance.guest.first_name %></h4>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<% end %>

<div class="mx-auto py-3" style="width: 600px;">
  <% if current_user == @event.administrator %>
    <button type="button" class="btn"><%= link_to "Modifier l'évenement", edit_event_path(@event.id), class: "btn
          btn-lg btn-info" %></button>
  <% end %>
</div>

app/views/attendances/update.html.erb
<h1>Attendances#update</h1>
<p>Find me in app/views/attendances/update.html.erb</p>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<div class="container">
	<% if current_user == @event.administrator %>
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Modifier l'évenement</h5>

            <%= form_for @event do |f| %>

             <div class="form-label-group">
              <%= f.text_field :title, class: "form-control", id: "inputTitle"  %>
          </div>

          <div class="form-label-group">
                <%= f.text_field :description, class: "form-control", id: "inputDescription" %>
              </div>

          <div class="form-label-group">
              <%= f.text_field :start_date, class: "form-control", id: "inputStart_date" %>
          </div>

          <div class="form-label-group">
              <%= f.text_field :duration, class: "form-control", id: "inputDuration"  %>
          </div>

          <div class="form-label-group">
                <%= f.text_field :price, class: "form-control", id: "inputPrice"  %>
              </div>

          <div class="form-label-group">
              <%= f.text_field :location, class: "form-control", id: "inputLocation" %>
          </div>

          <div class="form-group">
              <%= f.submit "Modifier Évenement", class: "btn btn-lg btn-info btn-block text-uppercase" %>
              <a href="<%= event_path(@event.id) %>" class= "btn btn-danger btn-block mt-3 text-uppercase" data-method="DELETE">Supprimer évenement</a>

          </div>
          </div>
        </div>
      </div>
    </div>
    	<% end %> 
   <% end %>
</div>

app/views/events/index.html.erb
<div class="mx-auto text-center">
	<div class="jumbotron">
	  <h1 class="display-4">Eventbrite</h1>
	  <p class="lead">Trouve ton prochain évenement préféré</p>
	  <% if user_signed_in? %>
	  <button type="button" class="btn"><%= link_to "Clique Ici pour créer un évenement", new_event_path , class: "btn
			    btn-lg btn-outline-info" %></button>
	  <% end %>
	</div>
</div>

<h2 class="text-center mb-3">Liste des évenements</h2>

<div class="container">
	<div class="card-deck mb-4 text-center">
		<% @events.each do |event| %>
		<div class="col-md-4">
			<div class="card border border-primary mt-3 shadow-sm" style="width: 18rem;">
			  <div class="card-body">
			    <h5 class="card-title mb-3"><%= event.title %></h5>
			    <h6 class="card-subtitle mb-5 text-muted"><%= event.administrator.first_name %></h6>
			    <% if user_signed_in? %>
			    <button type="button" class="btn"><%= link_to "Voir l'évenement", event_path(event.id), class: "btn
			    btn-md btn-info" %></button>
			    <% else %>
			    <button type="button" class="btn"><%= link_to "Voir l'évenement", new_user_session_path, class: "btn
			    btn-md btn-info" %></button>
			    <% end %>
			  </div>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/events/new.html.erb
<% if @event.errors.any? %>
   <div class="alert alert-danger text-center" role="alert">
 <p>Nous n'avons pas réussi à créer l'évenement' pour la (ou les) raison(s) suivante(s) :</p>
 <ul>
   <% @event.errors.full_messages.each do |message| %>
     <li><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>


<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Créer un évenement</h5>
            <%= form_tag url_for(action: 'create'), method: "post", class: "form-signin" do %>

             <div class="form-label-group">
            	<%= text_field_tag 'title', @title, class: "form-control", id: "inputTitle", placeholder: "Titre", :required => true  %>
      		</div>

      		<div class="form-label-group">
                <%= text_field_tag 'description', @description, class: "form-control", id: "inputDescription", placeholder: "Description", :required => true  %>
              </div>

      		<div class="form-label-group">
            	<%= text_field_tag 'start_date', @start_date, class: "form-control", id: "inputStart_date", placeholder: "Date", :required => true %>
      		</div>

      		<div class="form-label-group">
            	<%= text_field_tag 'duration', @duration, class: "form-control", id: "inputDuration", placeholder: "Durée", :required => true  %>
      		</div>

      		<div class="form-label-group">
                <%= text_field_tag 'price', @price, class: "form-control", id: "inputPrice", placeholder: "Prix", :required => true  %>
              </div>

      		<div class="form-label-group">
            	<%= text_field_tag 'location', @location, class: "form-control", id: "inputLocation", placeholder: "Lieu", :required => true %>
      		</div>

      		<div class="form-group">
            	<%= submit_tag "Créer Évenement", class: "btn btn-lg btn-info btn-block text-uppercase" %>
      		</div>
          </div>
        </div>
      </div>
    </div>
    <% end %>	
</div>

app/views/events/show.html.erb
<div class="mx-auto mt-3 py-3" style="width: 600px;">
<h1>Évenement</h1>
</div>

<div class="mx-auto py-3" style="width: 600px;">
<table class="table">
  <tbody>
    <tr>
      <th scope="row">Évenement</th>
      <td><%= @event.title %></td>
    </tr>
    <tr>
      <th scope="row">Description</th>
      <td><%= @event.description %></td>
    </tr>
    <tr>
      <th scope="row">Nombre de partipants</th>
      <td><%= @event.guests.count %></td>
    </tr>
    <tr>
      <th scope="row">Créateur</th>
      <td><%= @event.administrator.email %></td>
    </tr>
     <tr>
      <th scope="row">Date</th>
      <td><%= @event.start_date %></td>
    </tr>
    <tr>
      <th scope="row">Lieu</th>
      <td><%= @event.location %></td>
    </tr>
    <tr>
      <th scope="row">Prix</th>
      <td><%= @event.price %>€</td>
    </tr>
  </tbody>
</table>
</div>

<div class="mx-auto py-3" style="width: 600px;">
  <% unless current_user == @event.guests || current_user == @event.administrator %>

      <%= form_tag  do %>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
          <% end %>
          <label class="amount">
            <span>Prix: € <%= @event.price %></span>
          </label>
      </article>

      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="Participation à l'évenement"
              data-amount="<%= @event.price * 100 %>"
              data-currency="eur"
              data-locale="auto"></script>
    <% end %>
  <% end %>
</div>

<div class="mx-auto py-3" style="width: 600px;">
  <% if current_user == @event.administrator %>
    <button type="button" class="btn"><%= link_to "Voir les participants", attendance_path(@event.id), class: "btn
          btn-lg btn-info" %></button>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moussaillonsante</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>

     <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-white shadow">
    <div class="container">
      <a class="navbar-brand text-info" href="<%= root_path %>">Eventbrite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link text-info mr-2" href="<%= new_event_path %>">Créer un évenement</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-info mr-2" href="<%= users_path %>">Mon Profil</a>
          </li>
          <li class="nav-item">
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "nav-link text-info mr-2" %>
          </li>
          <% else %>
          <li class="nav-item">
            <a class="nav-link text-info mr-2" href="<%= new_user_session_path %>">Se connecter</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-info mr-2" href="<%= new_user_registration_path %>">S'inscrire</a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

    <%= yield %>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="container">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-muted">&copy; 2018-2019</small>
      </div>
      <div class="col-3">
        <h5 class="text-info">Menu</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="<%= root_path%>">Accueil </a></li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link text-info mr-2" href="<%= new_event_path %>">Créer un évenement</a>
          </li>
        <% end %>
        </ul>
      </div>
      <div class="col-3">
        <h5 class="text-info">Espace Membre</h5>
        <ul class="list-unstyled text-small">
          <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link text-info mr-2" href="<%= users_path %>">Mon Profil</a>
          </li>
          <li class="nav-item">
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "nav-link text-info mr-2" %>
          </li>
          <% else %>
          <li class="nav-item">
            <a class="nav-link text-info mr-2" href="<%= new_user_session_path %>">Se connecter</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-info mr-2" href="<%= new_user_registration_path %>">S'inscrire</a>
          </li>
          <% end %>
        </ul>
      </div>
      </div>
    </div>
  </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<div class="mx-auto mt-3 py-3" style="width: 600px;">
<h1>Profil Utilisateur</h1>
</div>

<div class="mx-auto py-3" style="width: 600px;">
<table class="table">
  <tbody>
    <tr>
      <th scope="row">Prénom</th>
      <td><%= current_user.first_name %></td>
    </tr>
    <tr>
      <th scope="row">Nom</th>
      <td><%= current_user.last_name %></td>
    </tr>
    <tr>
      <th scope="row">Description</th>
      <td><%= current_user.description %></td>
    </tr>
     <tr>
      <th scope="row">Mail</th>
      <td><%= current_user.email %></td>
    </tr>
  </tbody>
</table>
</div>

<div class="mx-auto mt-3 py-3" style="width: 600px;">
<h1>Évenement(s) de cet utilisateur</h1>
</div>

<div class="container">
	<div class="card-deck mb-4 text-center">
		<% current_user.events.each do |event| %>
		<div class="col-md-4">
			<div class="card border border-primary mt-3 shadow-sm" style="width: 18rem;">
			  <div class="card-body">
			    <h5 class="card-title mb-3"><%= event.title %></h5>
			    <button type="button" class="btn"><%= link_to "Voir l'évenement", event_path(event.id), class: "btn
			    btn-md btn-info" %></button>
			  </div>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="mx-auto mt-3 py-3" style="width: 600px;">
<h1>Profil Utilisateur</h1>
</div>

<div class="mx-auto py-3" style="width: 600px;">
<table class="table">
  <tbody>
    <tr>
      <th scope="row">Prénom</th>
      <td><%= @user.first_name %></td>
    </tr>
    <tr>
      <th scope="row">Nom</th>
      <td><%= @user.last_name %></td>
    </tr>
    <tr>
      <th scope="row">Description</th>
      <td><%= @user.description %></td>
    </tr>
     <tr>
      <th scope="row">Mail</th>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th scope="row">Évenement</th>
      <% @user.events.each do |event| %>
      <td><%= event.title %></td>
      <% end %>
    </tr>
  </tbody>
</table>
</div>